### ISSUE TITLE
Use of arrow functions in examples

### ISSUE THREAD

**Issue by 76784** [mawrkus/js-unit-testing-guide#10]
Thanks for the excellent guide. 

It is unclear to me whether the examples are using mocha or jasmine, as both of them use `describe()`. But I wanted to point out that mocha specifically discourages the use of arrow functions. https://mochajs.org/#arrow-functions

I think it would be helpful to make clear which framework/tooling the examples are using, and if they are indeed using mocha, they should perhaps use `function()` instead. Thanks.

**Comment by mawrkus** [comment]
Hello,

It is mentioned in the ["Guidelines" section](https://github.com/mawrkus/js-unit-testing-guide#guidelines): "All the following examples assume the usage of the Jasmine framework.".

In fact, I'd say that it's more Jest now than Mocha or Jasmine. Their syntax are quite similar, so it's a bit confusing indeed... I will figure out a way to make it more explicit, thank you for your feedback!

**Comment by 76784** [comment]
Ah! I didn't catch that guidelines section, my bad. Thanks very much!
